### 关于pandas的学习
### pandas是数据挖掘和数据分析中经常用到的库，关于学习pandas的基础，对于pandas的数据来说，就是有了行列标签的numpy类型数据


### 对于python语言中的pandas基础：
### 列表推导式于条件赋值

In [2]:
L=[]
def my_func(x):
    return 2*x

for i in range(5):
    L.append(my_func(i))
#     这里将my_func(i)计算后的内容添加到L列表中
L
# 对range（5）内的数值进行乘以2的操作
# 这里是利用循环

[0, 2, 4, 6, 8]

In [3]:
# 也可以简写
[my_func(i)for i in range(5)]


[0, 2, 4, 6, 8]

In [4]:
# for 可以嵌套
[m+'_'+n for m in ['a','b']for n in['c','d']]


['a_c', 'a_d', 'b_c', 'b_d']

### if语句也可以

In [5]:
value='cat' if 2>1 else 'dog'
value

'cat'

In [7]:
# 等价
a,b='cat','dog'
condition=2>1  #此时为true
if condition:
    value=a
else:
    value=b
    

In [8]:
L=[1,2,3,4,5,6,7]
[ i if i <=5 else 5 for i in L]

[1, 2, 3, 4, 5, 5, 5]

### 匿名函数与map方法
#### 映射函数

In [9]:
my_func=lambda x: 2*x
my_func(3)

6

In [10]:
multi_para_func=lambda a,b:a+b
multi_para_func(1,2)

3

In [11]:
[(lambda x:2*x)(i)for i in range(5)]


[0, 2, 4, 6, 8]

In [12]:
list(map(lambda x: 2*x,range(5)))

[0, 2, 4, 6, 8]

In [14]:
# 对多个数值的映射
list(map(lambda x,y:str(x)+'_'+y,range(5),list("abcde")))

['0_a', '1_b', '2_c', '3_d', '4_e']

### zip对象与enumerate方法

In [15]:
L1,L2,L3=list('abc'),list('def'),list('hij')
list(zip(L1,L2,L3))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [16]:
tuple(zip(L1,L2,L3))

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))

In [17]:
for i,j,k in zip(L1,L2,L3):
    print(i,j,k)

a d h
b e i
c f j


### enumerate是一种特殊的打包，可以在迭代的时候绑定迭代元素的遍历序号

In [18]:
L=list('abcd')
for index,value in enumerate(L):
    print(index,value)

0 a
1 b
2 c
3 d


In [19]:
# 也可以用zip实现】
for index,value in zip(range(len(L)),L):
    print(index,value)

0 a
1 b
2 c
3 d


In [20]:
# 也可以实现两个列表来建立字典映射
dict(zip(L1,L2))


{'a': 'd', 'b': 'e', 'c': 'f'}

In [22]:
zipped=list(zip(L1,L2,L3))
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [23]:
zipped=list(zip(L1,L2,L3))
print(zipped)
list(zip(*zipped))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]


[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

## numpy基础


### 创建多维数组一般有三种方式

In [24]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array(range(6))
c=np.arange(1,6)

In [27]:
# 特殊数组的生成
d=np.linspace(1,5,11)  # 类似于随机数组，起始位，终止位。样本个数
d

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [33]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [34]:
np.full((2,3),[1,2,3])

array([[1, 2, 3],
       [1, 2, 3]])

In [35]:
np.random.rand(3)


array([0.60933479, 0.79246115, 0.99615173])

In [36]:
np.random.rand(3,3)

array([[0.47869058, 0.85358244, 0.33509702],
       [0.79815457, 0.91209142, 0.88219786],
       [0.11991699, 0.515363  , 0.36647614]])

In [37]:
# 均与一年分布的数组
a,b=5,15
(b-a)*np.random.rand(3)+a

array([13.17600561,  9.69214463,  6.87874746])

In [38]:
np.random.randn(3)


array([ 1.34403071, -0.72528191, -1.65846067])

In [39]:
np.random.randn(2,2)

array([[-0.25830164, -0.75825359],
       [ 1.05240711,  0.5966113 ]])

In [40]:
# 正太分布
sigma,mu=2.5,3
mu+np.random.randn(3)*sigma

array([ 1.85790863, -0.7293065 ,  7.03575198])

In [41]:
# 随机生成数组时指定数组的最大值和最小值，维度
low,high,size=5,15,(2,2)
np.random.randint(low,high,size)

array([[13, 12],
       [ 5, 12]])

In [42]:
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])

array(['d', 'b'], dtype='<U1')

In [43]:
np.random.choice(my_list, (3,3))

array([['a', 'c', 'a'],
       ['b', 'c', 'd'],
       ['b', 'a', 'c']], dtype='<U1')

In [44]:
np.random.permutation(my_list)

array(['a', 'c', 'd', 'b'], dtype='<U1')

In [45]:
# 还可以设置随机种子，随机数种子相同，则生成的随机数也是相同的
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [46]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

### 对多维数组的操作
#### 对数组的转置有3中方法，transport、swapaxes，T

In [49]:

np.zeros((2,3)).T


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.zeros((2,3)).transpose()

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [51]:
np.zeros((2,3)).swapaxes(1,0)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### 数组的合并

In [53]:
np.r_[np.zeros((2,3)),np.zeros((2,3))]
# 纵向的合并

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]
# 横向的合并

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### 数组维度转换

In [55]:
t = np.arange(8).reshape(2,4)
t

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
t.reshape((4,2), order='C')  #按照行读取数据

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [58]:
t.reshape((4,2), order='F') # 按列读取数据

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In [60]:
t.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [62]:
t = np.ones((3,1))
t

array([[1.],
       [1.],
       [1.]])

In [63]:
t.reshape(-1)

array([1., 1., 1.])

### 数组的切片和索引

In [64]:
t = np.arange(9).reshape(3,3)
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
# 数组的切片模式支持使用 slice 类型的 start:end:step 切片，
# 还可以直接传入列表指定某个维度的索引进行切片：
t[:-1, [0,2]]

array([[0, 2],
       [3, 5]])

In [66]:
# 还可以利用 np.ix_ 在对应的维度上使用布尔索引，但此时不能使用 slice 切片：
t[np.ix_([True, False, True], [True, False, True])]   # 这里默认的是取第0行和第2行

array([[0, 2],
       [6, 8]])

In [67]:
t[np.ix_([1,2], [True, False, True])]  # 在前面的中括号中选择了行

array([[3, 5],
       [6, 8]])

In [70]:
# 对于numpy有很多的操作，这里的是选择符合要求的元素进行输出，也可修改值
a = np.array([-1,1,-1,0])
np.where(a>0, a, 5)

array([5, 1, 5, 5])

In [72]:
a = np.array([-2,-5,0,1,3,-1])
# nonzero 返回非零数的索引
np.nonzero(a)
#  argmax, argmin 分别返回最大和最小数的索引
a.argmax()


4

In [73]:
a.argmin()

1

In [74]:
a = np.array([0,1])
# any 指当序列至少 存在一个 True 或非零元素时返回 True ，否则返回 False
a.any()
# all 指当序列元素 全为 True 或非零元素时返回 True ，否则返回 False
a.all()

False

In [75]:
# cumprod, cumsum 分别表示累乘和累加函数，返回同长度的数组， 
# diff 表示和前一个元素做差，由于第一个元素为缺失值，
# 因此在默认参数情况下，返回长度是原数组减1
a = np.array([1,2,3])
a.cumprod()

array([1, 2, 6], dtype=int32)

In [76]:
a.cumsum()

array([1, 3, 6], dtype=int32)

In [77]:
np.diff(a)

array([1, 1])

In [78]:
# 常用的统计函数包括 max, min, mean, median, std, var, sum, quantile ，
# 其中分位数计算是全局方法，因此不能通过 array.quantile 的方法调用
t = np.arange(5)
t

array([0, 1, 2, 3, 4])

In [79]:
t.max()

4

In [80]:
np.quantile(t, 0.5)

2.0

In [81]:
# 缺失值nan
t = np.array([1, 2, np.nan])
t

array([ 1.,  2., nan])

In [82]:
t.max()

nan

In [83]:
 np.nanmax(t)

2.0

In [84]:
np.nanquantile(t, 0.5)

1.5

In [86]:
# 对于协方差和相关系数分别可以利用 cov, corrcoef 
t1 = np.array([1,3,5,9])
t2 = np.array([1,5,3,-9])
np.cov(t1, t2)

array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

In [87]:
np.corrcoef(t1, t2)

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

#### 需要说明二维 Numpy 数组中统计函数的 axis 参数，它能够进行某一个维度下的统计特征计算，当 axis=0 时结果为列的统计指标，当 axis=1 时结果为行的统计指标

In [88]:
t = np.arange(1,10).reshape(3,-1)
t


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
t.sum(0)

array([12, 15, 18])

In [90]:
t.sum(1)

array([ 6, 15, 24])

### 广播机制
#### 主要用于数组的计算

In [91]:
res = 3 * np.ones((2,2)) + 1

In [92]:
res

array([[4., 4.],
       [4., 4.]])

In [93]:
res=res/2
res

array([[2., 2.],
       [2., 2.]])

In [94]:
# 数组之间的运算也适用
res = np.ones((3,2))
res * np.array([[2,3]])

array([[2., 3.],
       [2., 3.],
       [2., 3.]])

In [95]:
 res * np.array([[2],[3],[4]])

array([[2., 2.],
       [3., 3.],
       [4., 4.]])

In [96]:
res * np.array([[2]])

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [97]:
np.ones(3) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [98]:
np.ones(3) + np.ones((2,1))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [99]:
np.ones(1) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

## 向量于矩阵的计算

In [100]:
a = np.array([1,2,3])
b = np.array([1,3,5])
a.dot(b)  # 内积

22

In [102]:
# 向量范数和矩阵范数： np.linalg.norm
t =  np.arange(4).reshape(-1,2)
t

array([[0, 1],
       [2, 3]])

In [103]:
np.linalg.norm(t, 'fro')

3.7416573867739413

In [104]:
np.linalg.norm(t, np.inf)

5.0

In [105]:
np.linalg.norm(t, 2)

3.702459173643833

In [107]:
t =  np.arange(4)
t

array([0, 1, 2, 3])

In [108]:
np.linalg.norm(t, np.inf)

3.0

In [109]:
np.linalg.norm(t, 2)

3.7416573867739413

In [110]:
np.linalg.norm(t, 3)

3.3019272488946263

In [111]:
a = np.arange(4).reshape(-1,2)
a

array([[0, 1],
       [2, 3]])

In [112]:
b = np.arange(-4,0).reshape(-1,2)
b

array([[-4, -3],
       [-2, -1]])

In [113]:
a@b  # 矩阵乘法

array([[ -2,  -1],
       [-14,  -9]])

### 利用列表推导式写矩阵乘法
#### 一般的矩阵乘法根据公式，可以由三重循环写出

In [114]:
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))

for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item
((M1@M2 - res) < 1e-15).all()

True